### ISSUE TITLE
cross site scripting

### ISSUE THREAD

**Issue by vu1n** [snipcart/snipcart-hexo-integration#1]
Promo code field of the snipcart is vulnerable to cross site scripting vulnerability leads to malicious java script execution and disclosure of snipcart order token.

**Preview on local build (video format)**

[snipcart_xss.zip](https://github.com/snipcart/snipcart-hexo-integration/files/4923199/snipcart_xss.zip)

**Preview on demo website**

![xss](https://user-images.githubusercontent.com/55493831/87509570-74c65780-c68f-11ea-874f-89e260a51baf.png)

**Comment by JeanSebTr** [comment]
Hi @vu1n !

This doesn't appear related to the Hexo demo?

Also, are you certain that this will cause an XSS? This doesn't appear to be a security concern if the user can only XSS himself. Anyone can already execute Javascript in the developer console.

**Comment by vu1n** [comment]
The js is injected into the promo code field not from the developer console, the promo code field must be sanitized from the malicious HTML or js. consider escaping malicious tags. (https://github.com/cure53/DOMPurify)

**Comment by vu1n** [comment]
The js is injected into the promo code field not from the developer console, the promo code field must be sanitized from the malicious HTML or js. consider escaping malicious tags. (https://github.com/cure53/DOMPurify)

**Comment by JeanSebTr** [comment]
@vu1n I understand this is a JS injection. However, if a customer can only inject is own session this doesn't appear to be a major concern. This is unfortunate and something we would fix ASAP if it was the V3 of the cart. The V2 being in maintenance-only mode, we won't invest time in this issue unless this pose a security risk to our merchants or customers.
